eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080

spring:
  mandatory-file-encoding: UTF-8
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true

paths:
  allowed: /api/admin,/api/auth,/api/user,/api/audit
  auth: http://user-server/api/auth/jwt-token

custom-response-sender:
  content:
    type: application/json